#!/bin/sh
export EDITOR="nvim"
export BROWSER="brave"
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/sqlite3:$PATH
export PATH=$HOME/nvim/bin:$PATH
export PATH="$HOME/.local/bin":$PATH
export PATH="/run/user/1000/fnm_multishells/38216_1767292053184/bin":$PATH
export FNM_MULTISHELL_PATH="/run/user/1000/fnm_multishells/38216_1767292053184"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/home/joseph/.local/share/fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_COREPACK_ENABLED="false"
export FNM_RESOLVE_ENGINES="true"
export FNM_ARCH="x64"
export GTK_THEME=Adwaita:dark
